/**
 * ─────────────────────────────────────────────────────
 *  SERVICES — Single source of truth for all services
 *  Used by: ServicesListing, FooterServices, sitemap
 *  Add / edit / remove a service here ONLY.
 * ─────────────────────────────────────────────────────
 */

export const SERVICES = [
  // ── 8 folder-based services (own image folders) ──
  {
    slug:         'dental-crowns',
    title:        'Dental Crowns & Bridges',
    footerLabel:  'Dental Crowns',
    desc:         'Custom-crafted zirconia, e.max, and PFM crowns and bridges for restoring damaged or missing teeth.',
    icon:         'bi-award-fill',
    gradient:     'linear-gradient(135deg, #d97706 0%, #b45309 100%)',
    accent:       '#d97706',
    image:        '/services/Dental-Crown/crown-zirconia.jpg',
    features:     ['Zirconia Crowns', 'e.max Crowns', 'PFM Crowns', 'Fixed Dental Bridges'],
  },
  {
    slug:         'dental-fillings',
    title:        'Dental Fillings',
    footerLabel:  'Dental Fillings',
    desc:         'Tooth-coloured composite fillings and precision ceramic inlays and onlays to restore decayed or damaged teeth in Tirupati.',
    icon:         'bi-palette',
    gradient:     'linear-gradient(135deg, #16a34a 0%, #15803d 100%)',
    accent:       '#16a34a',
    image:        '/services/Dental-filling/filling-decayed-tooth-composite.jpg',
    features:     ['Composite Fillings', 'Ceramic Inlays & Onlays', 'Single-Visit Option', '25× Microscope Precision'],
  },
  {
    slug:         'dentures',
    title:        'Dentures & Prosthetics',
    footerLabel:  'Dentures',
    desc:         'Premium BPS dentures, flexible partial dentures, and precision-crafted full dentures for a natural look.',
    icon:         'bi-person-fill',
    gradient:     'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    accent:       '#10b981',
    image:        '/services/denture-gallery/denture-complete.webp',
    features:     ['BPS Dentures', 'Flexible Dentures', 'Cast Partial Dentures', 'Implant-Supported Dentures'],
  },
  {
    slug:         'gum-treatment',
    title:        'Gum Treatment',
    footerLabel:  'Gum Treatment',
    desc:         'Comprehensive periodontal treatment — scaling, root planing, laser gum therapy, and long-term maintenance.',
    icon:         'bi-heart-pulse-fill',
    gradient:     'linear-gradient(135deg, #14b8a6 0%, #0284c7 100%)',
    accent:       '#14b8a6',
    image:        '/services/Gum/gum-scaling-root-planing.png',
    features:     ['Scaling & Root Planing', 'Laser Gum Therapy', 'Flap Surgery', 'Periodontal Maintenance'],
  },
  {
    slug:         'laser-dentistry',
    title:        'Laser Dentistry',
    footerLabel:  'Laser Dentistry',
    desc:         'Minimally invasive laser treatments for gum surgery, cavity treatment, ulcer healing, and gum contouring.',
    icon:         'bi-lightning-fill',
    gradient:     'linear-gradient(135deg, #f97316 0%, #dc2626 100%)',
    accent:       '#f97316',
    image:        '/services/Laser/laser-cover.png',
    features:     ['Laser Gum Surgery', 'Gum Contouring', 'Painless Cavity Prep', 'Ulcer Treatment'],
  },
  {
    slug:         'orthodontics',
    title:        'Orthodontic Treatment',
    footerLabel:  'Orthodontics',
    desc:         'Dental braces to align teeth for better straightening, jaw positioning, aesthetics, and facial symmetry.',
    icon:         'bi-emoji-smile',
    gradient:     'linear-gradient(135deg, #8b5cf6 0%, #db2777 100%)',
    accent:       '#8b5cf6',
    image:        '/services/Orthodontic/ortho-metal-braces.webp',
    features:     ['Metal Braces', 'Ceramic Braces', 'Self-Ligating Braces', '3D Oral Scanner Planning'],
  },
  {
    slug:         'pediatric-dentistry',
    title:        'Pediatric Dentistry',
    footerLabel:  'Pediatric',
    desc:         'Gentle, child-friendly dental care designed specially for children in a fun, fear-free environment.',
    icon:         'bi-heart-fill',
    gradient:     'linear-gradient(135deg, #ec4899 0%, #f43f5e 100%)',
    accent:       '#ec4899',
    image:        '/services/Pediatric/pediatric-fluoride-varnish.png',
    features:     ['Baby Teeth Care', 'Fluoride Treatment', 'Fissure Sealants', 'Space Maintainers'],
  },
  {
    slug:         'teeth-whitening',
    title:        'Teeth Whitening',
    footerLabel:  'Teeth Whitening',
    desc:         'Professional in-office laser whitening for a brighter, more confident smile in just one visit.',
    icon:         'bi-brightness-high-fill',
    gradient:     'linear-gradient(135deg, #f59e0b 0%, #ea580c 100%)',
    accent:       '#f59e0b',
    image:        '/services/teeth-whitening-gallery/whitening-cover.webp',
    features:     ['In-Office Laser Whitening', 'Take-Home Kits', 'Long-Lasting Results', 'Safe & Painless'],
  },
  // ── Remaining services ──
  {
    slug:         'smile-makeover',
    title:        'Smile Makeover',
    footerLabel:  'Smile Makeover',
    desc:         'Personalised combination of cosmetic and restorative treatments to transform your smile completely.',
    icon:         'bi-stars',
    gradient:     'linear-gradient(135deg, #a21caf 0%, #7c3aed 100%)',
    accent:       '#a21caf',
    image:        '/services/smile-makeover-cover.jpg',
    features:     ['Digital Smile Design', 'Porcelain Veneers', 'Gum Contouring', 'Composite Bonding'],
  },
  {
    slug:         'full-mouth-rehab',
    title:        'Full Mouth Rehabilitation',
    footerLabel:  'Full Mouth Rehab',
    desc:         'Complete smile reconstruction combining multiple specialist treatments for total oral health restoration.',
    icon:         'bi-layout-text-window-reverse',
    gradient:     'linear-gradient(135deg, #0f766e 0%, #1e3a5f 100%)',
    accent:       '#0f766e',
    image:        '/services/fmr-before-after-2.jpg',
    features:     ['Multi-Specialty Approach', 'Digital Treatment Planning', 'Implants + Crowns + Ortho', 'Phased Treatment'],
  },
  {
    slug:         'dental-implants',
    title:        'Dental Implants',
    footerLabel:  'Dental Implants',
    desc:         'Permanent, natural-looking tooth replacement with titanium implants. Our prosthodontists use cutting-edge implant systems for lifelong results.',
    icon:         'bi-hospital-fill',
    gradient:     'linear-gradient(135deg, #0ea5e9 0%, #0d9488 100%)',
    accent:       '#0ea5e9',
    image:        '/services/dental-implants.jpg',
    features:     ['Single & Multiple Implants', 'All-on-4 / All-on-6', 'Implant-Supported Dentures', 'Immediate Loading'],
  },
  {
    slug:         'root-canal',
    title:        'Root Canal Treatment',
    footerLabel:  'Root Canal',
    desc:         'Advanced, pain-free root canal using microscope-guided precision. Single-sitting RCT with highest success rates in Tirupati.',
    icon:         'bi-activity',
    gradient:     'linear-gradient(135deg, #3b82f6 0%, #7c3aed 100%)',
    accent:       '#3b82f6',
    image:        '/services/Root-Canal-Treatment.jpg',
    features:     ['Microscope-Guided RCT', 'Single-Sitting Available', 'Rotary Endodontics', 'Re-Root Canal Treatment'],
  },
  {
    slug:         'aligners',
    title:        'Clear Aligners & Invisalign',
    footerLabel:  'Clear Aligners',
    desc:         'Custom-fitted transparent trays that gradually shift teeth into position — invisible, removable, and comfortable.',
    icon:         'bi-gem',
    gradient:     'linear-gradient(135deg, #06b6d4 0%, #0891b2 100%)',
    accent:       '#0891b2',
    image:        '/services/aligners-img2.jpg',
    features:     ['Invisible Treatment', 'Invisalign Provider', '3D Intra-Oral Scanning', 'No Food Restrictions'],
  },
  {
    slug:         'microscope-dentistry',
    title:        'Microscope Dentistry',
    footerLabel:  'Microscope',
    desc:         'Experience the highest precision with dental microscope 25× dental operating microscope — only clinic in Tirupati.',
    icon:         'bi-search',
    gradient:     'linear-gradient(135deg, #4f46e5 0%, #0f766e 100%)',
    accent:       '#4f46e5',
    image:        '/images/microscope-treatment.jpg',
    features:     ['Precision Root Canals', 'Microsurgery', 'Crack Detection', 'Magnified Restorations'],
  },
  {
    slug:         'tooth-extraction',
    title:        'Tooth Extraction',
    footerLabel:  'Tooth Extraction',
    desc:         'Safe and comfortable tooth removal including impacted wisdom tooth surgery with minimal discomfort.',
    icon:         'bi-shield-fill-check',
    gradient:     'linear-gradient(135deg, #64748b 0%, #334155 100%)',
    accent:       '#64748b',
    image:        '/services/wisdom-img1.jpg',
    features:     ['Simple Extractions', 'Surgical Extractions', 'Wisdom Tooth Removal', 'OPG X-ray Planning'],
  },
];
